package com.xpu.school_guide.pojo;

public class AdminInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.admin
     *
     * @mbg.generated Sat Jun 20 21:50:09 CST 2020
     */
    private String admin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.password
     *
     * @mbg.generated Sat Jun 20 21:50:09 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.college_id
     *
     * @mbg.generated Sat Jun 20 21:50:09 CST 2020
     */
    private Integer collegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.admin
     *
     * @return the value of admin_info.admin
     *
     * @mbg.generated Sat Jun 20 21:50:09 CST 2020
     */
    public String getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.admin
     *
     * @param admin the value for admin_info.admin
     *
     * @mbg.generated Sat Jun 20 21:50:09 CST 2020
     */
    public void setAdmin(String admin) {
        this.admin = admin == null ? null : admin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.password
     *
     * @return the value of admin_info.password
     *
     * @mbg.generated Sat Jun 20 21:50:09 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.password
     *
     * @param password the value for admin_info.password
     *
     * @mbg.generated Sat Jun 20 21:50:09 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.college_id
     *
     * @return the value of admin_info.college_id
     *
     * @mbg.generated Sat Jun 20 21:50:09 CST 2020
     */
    public Integer getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.college_id
     *
     * @param collegeId the value for admin_info.college_id
     *
     * @mbg.generated Sat Jun 20 21:50:09 CST 2020
     */
    public void setCollegeId(Integer collegeId) {
        this.collegeId = collegeId;
    }
}