package com.xpu.school_guide.pojo;

public class Colleges {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colleges.id
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colleges.college_name
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    private String collegeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colleges.task_num
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    private Integer taskNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colleges.id
     *
     * @return the value of colleges.id
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colleges.id
     *
     * @param id the value for colleges.id
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colleges.college_name
     *
     * @return the value of colleges.college_name
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public String getCollegeName() {
        return collegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colleges.college_name
     *
     * @param collegeName the value for colleges.college_name
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName == null ? null : collegeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colleges.task_num
     *
     * @return the value of colleges.task_num
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public Integer getTaskNum() {
        return taskNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colleges.task_num
     *
     * @param taskNum the value for colleges.task_num
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public void setTaskNum(Integer taskNum) {
        this.taskNum = taskNum;
    }
}