package com.xpu.school_guide.pojo;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Groups {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.id
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.group_name
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.group_text
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    private String groupText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.group_order
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    private Integer groupOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.tasks_id
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    private Integer tasksId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.site_id
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    private Integer siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.is_delete
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */

    @JsonProperty("isDelete")
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.id
     *
     * @return the value of groups.id
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.id
     *
     * @param id the value for groups.id
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.group_name
     *
     * @return the value of groups.group_name
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.group_name
     *
     * @param groupName the value for groups.group_name
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.group_text
     *
     * @return the value of groups.group_text
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public String getGroupText() {
        return groupText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.group_text
     *
     * @param groupText the value for groups.group_text
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public void setGroupText(String groupText) {
        this.groupText = groupText == null ? null : groupText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.group_order
     *
     * @return the value of groups.group_order
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public Integer getGroupOrder() {
        return groupOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.group_order
     *
     * @param groupOrder the value for groups.group_order
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public void setGroupOrder(Integer groupOrder) {
        this.groupOrder = groupOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.tasks_id
     *
     * @return the value of groups.tasks_id
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public Integer getTasksId() {
        return tasksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.tasks_id
     *
     * @param tasksId the value for groups.tasks_id
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public void setTasksId(Integer tasksId) {
        this.tasksId = tasksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.site_id
     *
     * @return the value of groups.site_id
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.site_id
     *
     * @param siteId the value for groups.site_id
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.is_delete
     *
     * @return the value of groups.is_delete
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.is_delete
     *
     * @param isDelete the value for groups.is_delete
     *
     * @mbg.generated Fri May 15 18:48:25 CST 2020
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}