package com.xpu.school_guide.pojo;

public class StudentInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.open_id
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_id
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_name
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_status
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    private Byte studentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_school
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    private String studentSchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_college
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    private String studentCollege;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_major
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    private String studentMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_credent
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    private String studentCredent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.college_id
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    private Integer collegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.open_id
     *
     * @return the value of student_info.open_id
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.open_id
     *
     * @param openId the value for student_info.open_id
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_id
     *
     * @return the value of student_info.student_id
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_id
     *
     * @param studentId the value for student_info.student_id
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_name
     *
     * @return the value of student_info.student_name
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_name
     *
     * @param studentName the value for student_info.student_name
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_status
     *
     * @return the value of student_info.student_status
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public Byte getStudentStatus() {
        return studentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_status
     *
     * @param studentStatus the value for student_info.student_status
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public void setStudentStatus(Byte studentStatus) {
        this.studentStatus = studentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_school
     *
     * @return the value of student_info.student_school
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public String getStudentSchool() {
        return studentSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_school
     *
     * @param studentSchool the value for student_info.student_school
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public void setStudentSchool(String studentSchool) {
        this.studentSchool = studentSchool == null ? null : studentSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_college
     *
     * @return the value of student_info.student_college
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public String getStudentCollege() {
        return studentCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_college
     *
     * @param studentCollege the value for student_info.student_college
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public void setStudentCollege(String studentCollege) {
        this.studentCollege = studentCollege == null ? null : studentCollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_major
     *
     * @return the value of student_info.student_major
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public String getStudentMajor() {
        return studentMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_major
     *
     * @param studentMajor the value for student_info.student_major
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public void setStudentMajor(String studentMajor) {
        this.studentMajor = studentMajor == null ? null : studentMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_credent
     *
     * @return the value of student_info.student_credent
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public String getStudentCredent() {
        return studentCredent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_credent
     *
     * @param studentCredent the value for student_info.student_credent
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public void setStudentCredent(String studentCredent) {
        this.studentCredent = studentCredent == null ? null : studentCredent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.college_id
     *
     * @return the value of student_info.college_id
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public Integer getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.college_id
     *
     * @param collegeId the value for student_info.college_id
     *
     * @mbg.generated Tue Jun 30 23:23:59 CST 2020
     */
    public void setCollegeId(Integer collegeId) {
        this.collegeId = collegeId;
    }
}