package com.xpu.school_guide.pojo;

public class Tasks {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.id
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.task_name
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.task_text
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    private String taskText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.task_order
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    private Integer taskOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.college_id
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    private Integer collegeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.is_delete
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.is_first
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    private Boolean isFirst;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.id
     *
     * @return the value of tasks.id
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.id
     *
     * @param id the value for tasks.id
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.task_name
     *
     * @return the value of tasks.task_name
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.task_name
     *
     * @param taskName the value for tasks.task_name
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.task_text
     *
     * @return the value of tasks.task_text
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    public String getTaskText() {
        return taskText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.task_text
     *
     * @param taskText the value for tasks.task_text
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    public void setTaskText(String taskText) {
        this.taskText = taskText == null ? null : taskText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.task_order
     *
     * @return the value of tasks.task_order
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    public Integer getTaskOrder() {
        return taskOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.task_order
     *
     * @param taskOrder the value for tasks.task_order
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    public void setTaskOrder(Integer taskOrder) {
        this.taskOrder = taskOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.college_id
     *
     * @return the value of tasks.college_id
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    public Integer getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.college_id
     *
     * @param collegeId the value for tasks.college_id
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    public void setCollegeId(Integer collegeId) {
        this.collegeId = collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.is_delete
     *
     * @return the value of tasks.is_delete
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.is_delete
     *
     * @param isDelete the value for tasks.is_delete
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.is_first
     *
     * @return the value of tasks.is_first
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    public Boolean getIsFirst() {
        return isFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.is_first
     *
     * @param isFirst the value for tasks.is_first
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    public void setIsFirst(Boolean isFirst) {
        this.isFirst = isFirst;
    }
}