package com.xpu.school_guide.mapper;

import com.xpu.school_guide.pojo.Colleges;
import com.xpu.school_guide.pojo.CollegesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;

@Component
public interface CollegesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    long countByExample(CollegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    int deleteByExample(CollegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    int insert(Colleges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    int insertSelective(Colleges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    List<Colleges> selectByExampleWithRowbounds(CollegesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    List<Colleges> selectByExample(CollegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    Colleges selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") Colleges record, @Param("example") CollegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    int updateByExample(@Param("record") Colleges record, @Param("example") CollegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    int updateByPrimaryKeySelective(Colleges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    int updateByPrimaryKey(Colleges record);
}