package com.xpu.school_guide.mapper;

import com.xpu.school_guide.pojo.Sites;
import com.xpu.school_guide.pojo.SitesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;

@Component
public interface SitesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbg.generated Sat Jun 27 23:57:02 CST 2020
     */
    long countByExample(SitesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbg.generated Sat Jun 27 23:57:02 CST 2020
     */
    int deleteByExample(SitesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbg.generated Sat Jun 27 23:57:02 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbg.generated Sat Jun 27 23:57:02 CST 2020
     */
    int insert(Sites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbg.generated Sat Jun 27 23:57:02 CST 2020
     */
    int insertSelective(Sites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbg.generated Sat Jun 27 23:57:02 CST 2020
     */
    List<Sites> selectByExampleWithRowbounds(SitesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbg.generated Sat Jun 27 23:57:02 CST 2020
     */
    List<Sites> selectByExample(SitesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbg.generated Sat Jun 27 23:57:02 CST 2020
     */
    Sites selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbg.generated Sat Jun 27 23:57:02 CST 2020
     */
    int updateByExampleSelective(@Param("record") Sites record, @Param("example") SitesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbg.generated Sat Jun 27 23:57:02 CST 2020
     */
    int updateByExample(@Param("record") Sites record, @Param("example") SitesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbg.generated Sat Jun 27 23:57:02 CST 2020
     */
    int updateByPrimaryKeySelective(Sites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbg.generated Sat Jun 27 23:57:02 CST 2020
     */
    int updateByPrimaryKey(Sites record);
}