package com.xpu.school_guide.mapper;

import java.util.List;

import com.xpu.school_guide.pojo.StudentTasksGroups;
import com.xpu.school_guide.pojo.StudentTasksGroupsExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;

@Component
public interface StudentTasksGroupsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tasks_groups
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    long countByExample(StudentTasksGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tasks_groups
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    int deleteByExample(StudentTasksGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tasks_groups
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tasks_groups
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    int insert(StudentTasksGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tasks_groups
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    int insertSelective(StudentTasksGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tasks_groups
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    List<StudentTasksGroups> selectByExampleWithRowbounds(StudentTasksGroupsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tasks_groups
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    List<StudentTasksGroups> selectByExample(StudentTasksGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tasks_groups
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    StudentTasksGroups selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tasks_groups
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") StudentTasksGroups record, @Param("example") StudentTasksGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tasks_groups
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    int updateByExample(@Param("record") StudentTasksGroups record, @Param("example") StudentTasksGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tasks_groups
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    int updateByPrimaryKeySelective(StudentTasksGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tasks_groups
     *
     * @mbg.generated Fri May 15 18:44:11 CST 2020
     */
    int updateByPrimaryKey(StudentTasksGroups record);
}