package com.xpu.school_guide.mapper;

import com.xpu.school_guide.pojo.Tasks;
import com.xpu.school_guide.pojo.TasksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;

@Component
public interface TasksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    long countByExample(TasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    int deleteByExample(TasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    int insert(Tasks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    int insertSelective(Tasks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    List<Tasks> selectByExampleWithRowbounds(TasksExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    List<Tasks> selectByExample(TasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    Tasks selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") Tasks record, @Param("example") TasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    int updateByExample(@Param("record") Tasks record, @Param("example") TasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    int updateByPrimaryKeySelective(Tasks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jun 22 23:20:47 CST 2020
     */
    int updateByPrimaryKey(Tasks record);
}